
version :"3"
services:

  front:

    build:

      context:"./client"
      dockerfile:Dockerfile

    ports:

      - 5173:5173

    container_name:react-container

    networks:
      - mern-stack-network
    
    depends_on:

      - backend
  
  backend:

    build:

      context:"./server"
      dockerfile:Dockerfile

    ports:

      - 3001:3001

    env_file:
      - ./server/.env

    container_name:server-container

    networks:
      - mern-stack-network


networks:
  mern-stack-network:


    
    
